name: Feature Request
description: Use este formulário para sugerir uma nova funcionalidade ou melhoria.
title: "[FEATURE] Descrição concisa da proposta"
labels: ["enhancement"]

body:
  - type: textarea
    attributes:
      label: Problema ou Necessidade
      description: Descreva qual problema ou necessidade esta funcionalidade resolveria.
      placeholder: Ex: "Atualmente não é possível exportar relatórios em PDF, o que dificulta o compartilhamento."
    validations:
      required: true

  - type: textarea
    attributes:
      label: Solução Proposta
      description: Descreva de forma clara a funcionalidade ou melhoria que você está sugerindo.
      placeholder: Ex: "Adicionar opção para exportar relatórios em PDF na tela de relatórios."
    validations:
      required: true

  - type: textarea
    attributes:
      label: Benefícios
      description: Explique como essa funcionalidade ajudaria os usuários ou o sistema.
      placeholder: Ex: "Facilitaria o compartilhamento de informações."
    validations:
      required: false

  - type: textarea
    attributes:
      label: Alternativas Consideradas
      description: Liste outras soluções ou ideias que você pensou antes.
      placeholder: Ex: "Criei um script externo para fazer X coisa por fora, mas pelo sistema ficaria melhor."
    validations:
      required: false

  - type: textarea
    attributes:
      label: Contexto Adicional
      description: Adicione prints de tela, exemplos ou links que ajudem a entender melhor a sugestão.
      placeholder: Você pode colar imagens ou links aqui.
    validations:
      required: false
